### ISSUE TITLE
Migration tool doesn't find services with "-local" suffix

### ISSUE THREAD

**Issue by pgier** [datastax/kaap#116]
We have services configured with a "-local" suffix.  When running the migration tool against this cluster, it fails with this error:
```
17:09:49.469 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
Exception in thread "main" java.lang.IllegalStateException: Expected service with name mycluster-proxy not found
	at com.datastax.oss.kaap.migrationtool.specs.BaseSpecGenerator.getService(BaseSpecGenerator.java:142)
	at com.datastax.oss.kaap.migrationtool.specs.BaseSpecGenerator.requireService(BaseSpecGenerator.java:133)
	at com.datastax.oss.kaap.migrationtool.specs.ProxySetSpecGenerator.internalGenerateSpec(ProxySetSpecGenerator.java:82)
	at com.datastax.oss.kaap.migrationtool.specs.ProxySetSpecGenerator.<init>(ProxySetSpecGenerator.java:59)
	at com.datastax.oss.kaap.migrationtool.specs.ProxySpecGenerator.internalGenerateSpec(ProxySpecGenerator.java:53)
	at com.datastax.oss.kaap.migrationtool.specs.ProxySpecGenerator.<init>(ProxySpecGenerator.java:46)
	at com.datastax.oss.kaap.migrationtool.PulsarClusterResourceGenerator.<init>(PulsarClusterResourceGenerator.java:72)
	at com.datastax.oss.kaap.migrationtool.SpecGenerator.generatePulsarClusterSpec(SpecGenerator.java:153)
	at com.datastax.oss.kaap.migrationtool.SpecGenerator.generate(SpecGenerator.java:132)
	at com.datastax.oss.kaap.migrationtool.SpecGenerator.generate(SpecGenerator.java:119)
	at com.datastax.oss.kaap.migrationtool.Main$GenerateCmd.run(Main.java:98)
	at com.datastax.oss.kaap.migrationtool.Main.main(Main.java:73)

**Comment by nicoloboschi** [comment]
What are `local` services? What is the logic behind it?
would a new option to configure the name suffix be sufficient ?

**Comment by pgier** [comment]
@michaeljmarshall can probably provide more context, I think the -local suffix on our services was a workaround to avoid deleting the existing services: https://github.com/riptano/astra-streaming/pull/900

**Comment by pgier** [comment]
Yes, I think adding a new option to allow a suffix would probably be enough.
